[2019-07-30 19:00:47,705] {/home/alta6/.virtualenv/rest_practice/lib/python3.6/site-packages/flask/app.py:1891} ERROR - Exception on /person [GET]
Traceback (most recent call last):
  File "/home/alta6/.virtualenv/rest_practice/lib/python3.6/site-packages/flask/app.py", line 1949, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/alta6/.virtualenv/rest_practice/lib/python3.6/site-packages/flask/app.py", line 1935, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/home/alta6/.virtualenv/rest_practice/lib/python3.6/site-packages/flask_restful/__init__.py", line 458, in wrapper
    resp = resource(*args, **kwargs)
  File "/home/alta6/.virtualenv/rest_practice/lib/python3.6/site-packages/flask/views.py", line 89, in view
    return self.dispatch_request(*args, **kwargs)
  File "/home/alta6/.virtualenv/rest_practice/lib/python3.6/site-packages/flask_restful/__init__.py", line 573, in dispatch_request
    resp = meth(*args, **kwargs)
TypeError: get() missing 1 required positional argument: 'id'
[2019-07-30 19:00:47,712] {/home/alta6/ALTERRA_ACADEMY/RESTful-D1/rest_svc/blueprints/__init__.py:35} WARNING - REQUEST_LOG	{"uri": "/person?", "code": "500 INTERNAL SERVER ERROR", "method": "GET", "request": {}, "response": {"message": "Internal Server Error"}}
[2019-07-30 19:01:28,315] {/home/alta6/.virtualenv/rest_practice/lib/python3.6/site-packages/flask/app.py:1891} ERROR - Exception on /person [GET]
Traceback (most recent call last):
  File "/home/alta6/.virtualenv/rest_practice/lib/python3.6/site-packages/flask/app.py", line 1949, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/alta6/.virtualenv/rest_practice/lib/python3.6/site-packages/flask/app.py", line 1935, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/home/alta6/.virtualenv/rest_practice/lib/python3.6/site-packages/flask_restful/__init__.py", line 458, in wrapper
    resp = resource(*args, **kwargs)
  File "/home/alta6/.virtualenv/rest_practice/lib/python3.6/site-packages/flask/views.py", line 89, in view
    return self.dispatch_request(*args, **kwargs)
  File "/home/alta6/.virtualenv/rest_practice/lib/python3.6/site-packages/flask_restful/__init__.py", line 573, in dispatch_request
    resp = meth(*args, **kwargs)
TypeError: get() missing 1 required positional argument: 'id'
[2019-07-30 19:01:28,316] {/home/alta6/ALTERRA_ACADEMY/RESTful-D1/rest_svc/blueprints/__init__.py:35} WARNING - REQUEST_LOG	{"uri": "/person?", "code": "500 INTERNAL SERVER ERROR", "method": "GET", "request": {}, "response": {"message": "Internal Server Error"}}
[2019-07-30 19:01:54,916] {/home/alta6/.virtualenv/rest_practice/lib/python3.6/site-packages/flask/app.py:1891} ERROR - Exception on /person [GET]
Traceback (most recent call last):
  File "/home/alta6/.virtualenv/rest_practice/lib/python3.6/site-packages/flask/app.py", line 1949, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/alta6/.virtualenv/rest_practice/lib/python3.6/site-packages/flask/app.py", line 1935, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/home/alta6/.virtualenv/rest_practice/lib/python3.6/site-packages/flask_restful/__init__.py", line 458, in wrapper
    resp = resource(*args, **kwargs)
  File "/home/alta6/.virtualenv/rest_practice/lib/python3.6/site-packages/flask/views.py", line 89, in view
    return self.dispatch_request(*args, **kwargs)
  File "/home/alta6/.virtualenv/rest_practice/lib/python3.6/site-packages/flask_restful/__init__.py", line 573, in dispatch_request
    resp = meth(*args, **kwargs)
TypeError: get() missing 1 required positional argument: 'id'
[2019-07-30 19:01:54,918] {/home/alta6/ALTERRA_ACADEMY/RESTful-D1/rest_svc/blueprints/__init__.py:35} WARNING - REQUEST_LOG	{"uri": "/person?", "code": "500 INTERNAL SERVER ERROR", "method": "GET", "request": {}, "response": {"message": "Internal Server Error"}}
[2019-07-30 19:01:58,042] {/home/alta6/ALTERRA_ACADEMY/RESTful-D1/rest_svc/blueprints/__init__.py:35} WARNING - REQUEST_LOG	{"uri": "/person/?", "code": "404 NOT FOUND", "method": "GET", "request": {}, "response": {"message": "The requested URL was not found on the server. If you entered the URL manually please check your spelling and try again."}}
[2019-07-30 19:02:01,105] {/home/alta6/ALTERRA_ACADEMY/RESTful-D1/rest_svc/blueprints/__init__.py:35} WARNING - REQUEST_LOG	{"uri": "/person/2?", "code": "404 NOT FOUND", "method": "GET", "request": {}, "response": {"status": "NOT_FOUND"}}
[2019-07-30 19:02:07,838] {/home/alta6/ALTERRA_ACADEMY/RESTful-D1/rest_svc/blueprints/__init__.py:35} WARNING - REQUEST_LOG	{"uri": "/person/2?", "code": "404 NOT FOUND", "method": "GET", "request": {}, "response": {"status": "NOT_FOUND"}}
[2019-07-30 19:02:14,440] {/home/alta6/.virtualenv/rest_practice/lib/python3.6/site-packages/flask/app.py:1891} ERROR - Exception on /person [GET]
Traceback (most recent call last):
  File "/home/alta6/.virtualenv/rest_practice/lib/python3.6/site-packages/flask/app.py", line 1949, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/alta6/.virtualenv/rest_practice/lib/python3.6/site-packages/flask/app.py", line 1935, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/home/alta6/.virtualenv/rest_practice/lib/python3.6/site-packages/flask_restful/__init__.py", line 458, in wrapper
    resp = resource(*args, **kwargs)
  File "/home/alta6/.virtualenv/rest_practice/lib/python3.6/site-packages/flask/views.py", line 89, in view
    return self.dispatch_request(*args, **kwargs)
  File "/home/alta6/.virtualenv/rest_practice/lib/python3.6/site-packages/flask_restful/__init__.py", line 573, in dispatch_request
    resp = meth(*args, **kwargs)
TypeError: get() missing 1 required positional argument: 'id'
[2019-07-30 19:02:14,441] {/home/alta6/ALTERRA_ACADEMY/RESTful-D1/rest_svc/blueprints/__init__.py:35} WARNING - REQUEST_LOG	{"uri": "/person?", "code": "500 INTERNAL SERVER ERROR", "method": "GET", "request": {}, "response": {"message": "Internal Server Error"}}
[2019-07-30 19:02:18,113] {/home/alta6/.virtualenv/rest_practice/lib/python3.6/site-packages/flask/app.py:1891} ERROR - Exception on /person [GET]
Traceback (most recent call last):
  File "/home/alta6/.virtualenv/rest_practice/lib/python3.6/site-packages/flask/app.py", line 1949, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/alta6/.virtualenv/rest_practice/lib/python3.6/site-packages/flask/app.py", line 1935, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/home/alta6/.virtualenv/rest_practice/lib/python3.6/site-packages/flask_restful/__init__.py", line 458, in wrapper
    resp = resource(*args, **kwargs)
  File "/home/alta6/.virtualenv/rest_practice/lib/python3.6/site-packages/flask/views.py", line 89, in view
    return self.dispatch_request(*args, **kwargs)
  File "/home/alta6/.virtualenv/rest_practice/lib/python3.6/site-packages/flask_restful/__init__.py", line 573, in dispatch_request
    resp = meth(*args, **kwargs)
TypeError: get() missing 1 required positional argument: 'id'
[2019-07-30 19:02:18,114] {/home/alta6/ALTERRA_ACADEMY/RESTful-D1/rest_svc/blueprints/__init__.py:35} WARNING - REQUEST_LOG	{"uri": "/person?", "code": "500 INTERNAL SERVER ERROR", "method": "GET", "request": {}, "response": {"message": "Internal Server Error"}}
[2019-07-30 19:02:20,379] {/home/alta6/.virtualenv/rest_practice/lib/python3.6/site-packages/flask/app.py:1891} ERROR - Exception on /person [GET]
Traceback (most recent call last):
  File "/home/alta6/.virtualenv/rest_practice/lib/python3.6/site-packages/flask/app.py", line 1949, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/alta6/.virtualenv/rest_practice/lib/python3.6/site-packages/flask/app.py", line 1935, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/home/alta6/.virtualenv/rest_practice/lib/python3.6/site-packages/flask_restful/__init__.py", line 458, in wrapper
    resp = resource(*args, **kwargs)
  File "/home/alta6/.virtualenv/rest_practice/lib/python3.6/site-packages/flask/views.py", line 89, in view
    return self.dispatch_request(*args, **kwargs)
  File "/home/alta6/.virtualenv/rest_practice/lib/python3.6/site-packages/flask_restful/__init__.py", line 573, in dispatch_request
    resp = meth(*args, **kwargs)
TypeError: get() missing 1 required positional argument: 'id'
[2019-07-30 19:02:20,380] {/home/alta6/ALTERRA_ACADEMY/RESTful-D1/rest_svc/blueprints/__init__.py:35} WARNING - REQUEST_LOG	{"uri": "/person?", "code": "500 INTERNAL SERVER ERROR", "method": "GET", "request": {}, "response": {"message": "Internal Server Error"}}
[2019-07-30 19:02:25,278] {/home/alta6/.virtualenv/rest_practice/lib/python3.6/site-packages/flask/app.py:1891} ERROR - Exception on /person [GET]
Traceback (most recent call last):
  File "/home/alta6/.virtualenv/rest_practice/lib/python3.6/site-packages/flask/app.py", line 1949, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/alta6/.virtualenv/rest_practice/lib/python3.6/site-packages/flask/app.py", line 1935, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/home/alta6/.virtualenv/rest_practice/lib/python3.6/site-packages/flask_restful/__init__.py", line 458, in wrapper
    resp = resource(*args, **kwargs)
  File "/home/alta6/.virtualenv/rest_practice/lib/python3.6/site-packages/flask/views.py", line 89, in view
    return self.dispatch_request(*args, **kwargs)
  File "/home/alta6/.virtualenv/rest_practice/lib/python3.6/site-packages/flask_restful/__init__.py", line 573, in dispatch_request
    resp = meth(*args, **kwargs)
TypeError: get() missing 1 required positional argument: 'id'
